import fs from 'fs';
import jwt from 'jsonwebtoken';
import path from 'path';
import { db } from './server/db/index.ts';
import { users } from './server/db/schema.ts';
import { eq } from 'drizzle-orm';

async function run() {
  const adminUsers = await db.select().from(users).where(eq(users.role, 'administrator')).limit(1);
  if (adminUsers.length === 0) {
    console.error("No admins found in database!");
    process.exit(1);
  }
  const admin = adminUsers[0];
  
  const JWT_SECRET = process.env.JWT_SECRET || 'fallback_secret_for_dev';
  const token = jwt.sign({ id: admin.id, username: admin.username, role: 'administrator' }, JWT_SECRET);
  
  const mockTtf = Buffer.concat([
    Buffer.from([0x00, 0x01, 0x00, 0x00]),
    Buffer.from('dummy font data')
  ]);
  
  console.log('--- 1. Uploading Font ---');
  const uploadRes = await fetch('http://localhost:3000/api/karaoke/settings/lyrics/custom-font?filename=test_font.ttf', {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer ' + token,
      'Content-Type': 'font/ttf',
      'x-font-filename': 'test_font.ttf'
    },
    body: mockTtf
  });
  
  const uploadData = await uploadRes.json();
  console.log('Upload Status:', uploadRes.status);
  
  if (uploadRes.status !== 200) {
    console.error('Upload failed!', uploadData);
    process.exit(1);
  }
  
  const fontId = uploadData.settings.customFontId;
  console.log('Font ID generated by server:', fontId);
  
  console.log('\n--- 2. Checking File System ---');
  const fontPath = path.join(process.cwd(), 'data', 'fonts', fontId);
  const exists = fs.existsSync(fontPath);
  console.log('File created on disk?', exists);
  
  console.log('\n--- 3. Checking Database / Settings API ---');
  const settingsRes = await fetch('http://localhost:3000/api/karaoke/settings/lyrics', {
    headers: { 'Authorization': 'Bearer ' + token }
  });
  const settingsData = await settingsRes.json();
  console.log('Settings API fontId:', settingsData.settings.customFontId);
  console.log('Settings API match?', settingsData.settings.customFontId === fontId);
  
  console.log('\n--- 4. Checking Font Serving API ---');
  const serveRes = await fetch(`http://localhost:3000/api/karaoke/settings/lyrics/custom-font/${fontId}`);
  console.log('Serve API Status:', serveRes.status);
  console.log('Serve API Content-Type:', serveRes.headers.get('content-type'));
  
  process.exit(0);
}
run().catch(err => { console.error(err); process.exit(1); });
